name: 'Jest Diff Coverage'
description:
  'The Jest Diff Coverage Action is a GitHub Action that helps you manage code
  coverage differentials in your Jest test suites. This action provides insights
  into the coverage changes between different commits or branches, allowing you
  to track and manage test coverage improvements or regressions.'
author: 'Jean-Pierre Carvalho'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  milliseconds:
    description: 'Your input description here'
    required: true
    default: '1000'

# Define your outputs here.
outputs:
  time:
    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
